### ISSUE TITLE
Can't exclude the sitemap itself from indexing

### ISSUE THREAD

**Issue by Gallenkamp** [Sterc/SEOTab#45] opened 2015-08-03 16:31 UTC
Sitemap itself is beeing indexed:

http://vonbohr-fescharek.de/sitemap.xml

Both settings are set to "no", regarding indexing. Sitemap is published but not visible in menu.

**Comment by Gallenkamp** [comment] 2015-08-03 16:36
For now, I copied the sitemap output, edited and published a hardcoded version.

**Comment by Bumme** [comment] 2015-09-11 05:09
Could you check if it's fixed in the new release? I can't reproduce this issue.

**Comment by sdrenth** [comment] 2015-12-04 09:20
@Gallenkamp is this issue fixed now with the latest release? Else i'm going to close this issue

**Closed** 2015-12-18 07:59 UTC

**Comment by Gallenkamp** [comment] 2015-12-18 08:09
Will check immedieately.

**Comment by Gallenkamp** [comment] 2015-12-18 08:23
Sitemap can be excluded. Thank you!

**Comment by sdrenth** [comment] 2015-12-18 08:29
Glad to hear! ;)
