### ISSUE TITLE
Changing the template before saving a new resource ignores search_default

### ISSUE THREAD

**Issue by labr1005** [Sterc/SEOTab#41] opened 2015-03-07 17:04 UTC
System Setting search_default = 1

Create a new resource > searchable = 1.
Change the template before saving the resource > searchable = 0.

**Comment by sdrenth** [comment] 2015-12-04 11:01
I was unable to reproduce this issue, but i think it was a modx related issue that has already been fixed. So i'm closing this issue for now.

**Closed** 2015-12-04 11:01 UTC
