### ISSUE TITLE
Errors during installation of SEO Tab 2.0.4 on MODX 2.6.0

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#140] opened 2017-12-13 15:17 UTC
![screen shot 2017-12-13 at 16 16 34](https://user-images.githubusercontent.com/381017/33946075-18f225da-e021-11e7-9054-3027cd2df32f.png)

**Comment by gpsietzema** [comment] 2017-12-13 15:22
Extra info: on windows 10 + chrome some users report a crashing browser when click the 'SEO' Tab in a resource.

![error](https://user-images.githubusercontent.com/381017/33946317-c1c38e9c-e021-11e7-82a5-f6716b0373cb.png)

**Comment by asjer** [comment] 2017-12-20 21:16
I get the exact same error when installing the plugin.

**Comment by MrRoco** [comment] 2018-01-23 10:52
Hello GP,

The installation error is fixed with 2.0.5.
I'll add the crash in Windows 10 + chrome to the roadmap.

**Comment by sdrenth** [comment] 2018-09-21 08:40
Since the installation error is already fixed and I cannot reproduce the Windows 10 + Chrome bug I'll close this issue.

I've tested with Windows 10 + Chrome and Windows 10 + IE 11 and the (related) installed package Formit 4.1.0 and SEO Tab 2.0.5

**Closed as completed by sdrenth** 2018-09-21 08:40 UTC
