### ISSUE TITLE
No title in Google Preview with Chrome

### ISSUE THREAD

**Issue by crimsonpixel** [Sterc/SEOTab#127] opened 2017-09-06 19:53 UTC
When viewing the resource with Firefox you can clearly see the page (or long) title in the Google Preview box, however, in Chrome it isn't visible....

First viewis in Firefox with title

![ff-view](https://user-images.githubusercontent.com/2063237/30131588-3e651bca-9345-11e7-86de-27ff6fc10720.png)

Second view of same resource in Chrome and no title being displayed...

![chrome-view](https://user-images.githubusercontent.com/2063237/30131629-5e23072e-9345-11e7-808e-8f83a37fbfa0.png)

Bug?

**Comment by joeke** [comment] 2017-09-07 07:04
That is strange behaviour indeed. All looks fine on Chrome here.. Do you have any console errors? And what are the versions you're using (Chrome/MODX/SEOTab)?

**Comment by sdrenth** [comment] 2018-08-13 12:02
@crimsonpixel  I'm going to close this issue since we are unable to reproduce this error and no further information has been provided.

**Closed by sdrenth** 2018-08-13 12:02 UTC
