### ISSUE TITLE
Undefined variable: urls in SEOtab plugin when creating a new page

### ISSUE THREAD

**Issue by Lefthandmedia** [Sterc/SEOTab#142] opened 2017-12-21 14:03 UTC
Hi when i turn SEOtab on the manager and i try to create a new page the manger stops loading and becomes unusable because there is a an error in OnDocFormPrerender on line 71
` if ($urls && is_object($urls)) {`

**Comment by MrRoco** [comment] 2018-01-23 10:42
Hello,

Sorry to hear you're having some troubles with SEOTab.
Can you provide us with some more information so we can try to reproduce your errors.
- SEOTab version
- MODx version
- PHP version

Also was it a custom page like an simplecart page or collections of sorts ?

**Comment by sdrenth** [comment] 2018-08-13 12:28
@Lefthandmedia I'm going to close this issue since you haven't been responding on this issue. If the issue still remains, please provide us the information as asked and we will look into it.

**Closed as completed by sdrenth** 2018-08-13 12:28 UTC

**Comment by cured** [comment] 2018-12-18 19:27
Hello
i got the same issue
stercseo-2.1.0-pl
modx revolution-2.6.5 pl
php 7.1.25
