### ISSUE TITLE
Seo tab visibility managment using form customization

### ISSUE THREAD

**Issue by ExcaliburKG** [Sterc/SEOTab#39] opened 2015-02-18 21:18 UTC
I've tried to hide the seo tab from particular user group using modx built-in manager form customization with no success - there's no panel id to hide in region settings. Is it an expected behavior  of current build or am I missing something?

**Comment by labr1005** [comment] 2015-03-07 17:19
Create a new plugin.
```
<?php
if ($modx->user->isMember('Administrator')) {
    return;
}
$modx->regClientStartupHTMLBlock('<style>
#modx-resource-tabs__seo-tab {
    display: none !important;
}
</style>');
```
Check "System Events" > "OnDocFormPrerender".

**Comment by joeke** [comment] 2015-12-04 10:54
Hi @ExcaliburKG,
This is indeed expected behaviour; the SEO tab is not available via the modx form customization, due to the fact that it is added via a plugin. You could use the solution provided by @labr1005 but it could be a nice addition to add a system setting to exclude / include usergroups from displaying SEOTab. 
We're scheduling this for a next release. Thanks for your feedback guys!

**Comment by sdrenth** [comment] 2015-12-18 11:02
I've added the systemsetting to exclude usergroups from seeing the seotab. It will be included in our next release!

**Comment by EkoOne** [comment] 2016-05-04 03:56
I'm curious, has there been any progress on the user-groups feature request?

**Comment by joeke** [comment] 2016-09-09 19:29
@EkoOne This will be part of the upcoming release of SEOTab, which will be released in the next few days.

**Comment by joeke** [comment] 2017-01-25 14:29
@gpsietzema I've tested this and can confirm this works. System setting `stercseo.hide_from_usergroups` can be configured to exclude user groups from viewing SEO Tab.

**Closed by joeke** 2017-01-25 14:29 UTC
Labels: enhancement, In progress

**Comment by EkoOne** [comment] 2017-01-25 19:30
That's great!
